server :
  port : 2508
  
spring:

  security:
    user:
      name: Thai
      password: 2508

  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: 2508
   
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver

